jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / ..... etc>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Dandilion'
          options: --onefile, --name "Dandilion", --windowed,  --icon "assets/Icon.ico"
